### ISSUE TITLE
The Extension Only Works When Prophet is Disabled

### ISSUE THREAD

**Issue by FabiowQuixada** [FabiowQuixada/vscode-isml-linter#3]
If you disable Prophet Debugger extension and reload VS Code, Isml Linter extension works as expected.

Will investigate why this conflict happens.

**Comment by SqrTT** [comment]
this is happening because isml-linter activates on `xml` extension but if you enable prophet then prophet makes new type of files `isml` so your extension don't see them anymore

please add in activation section:
```json
	"activationEvents": [
		"onLanguage:xml",
                "onLanguage:isml" <--
	],
```
and align documentSelector:
```js
documentSelector: [{ scheme: 'file', language: 'xml' }, { scheme: 'file', language: 'isml' }],
```

**Comment by FabiowQuixada** [comment]
Hello @SqrTT ,

I did the change and it works as expected.

Thanks for the help!
